### PR TITLE
Update atomes.spec

### PR DESCRIPTION
**Pull request by alxpl**
Hi Sébastien,
I took a quick look and made some corrections to the spec file cosmetic (frenchisms, weird ligatures, etc.) and others. Your changelog entries need to have the  (E)VR information at the end. When you make a new build, but there is no code change in the package upstream, you just increment the release, both in the "Release:" field and in the changelog. Also, note that you are writing the changelog from the perspective of the packager and not the upstream developer (which is often confusing when you are both). This means that you note things like new program versions, a patch you may have included, a rebuild against a newer version of a dependency etc.. While I was able to replace `make install` with the `%make_install` macro, I could not replace `make` with `%make_build` in the build phase. On my computer, the macro evaluates to
```
$ rpm --eval %make_build
/usr/bin/make -O -j8 V=1 VERBOSE=1
```
I'm guessing that something might be wrong with parallel builds, as I would always get a complaint about a missing file - I think parameters.mod or something like that.

These changes should make the linter complain a bit less, if you have any questions, don't hesitate to ask.

### CODE REVIEW

**Review by Slookeur — APPROVED** [review]

**Comment by Slookeur** [comment]
Thank you so much !
Worked on that all day on trying to improve things, added a gpg section required in the packaging guide line:
```
Source0:        https://github.com/Slookeur/Atomes-rpm-build/raw/main/%{name}-%{version}.tar.gz
Source1:        https://github.com/Slookeur/Atomes-rpm-build/raw/main/%{name}-%{version}.tar.gz.asc
Source2:        https://github.com/Slookeur/Atomes-rpm-build/raw/main/atomes.gpg
``` 
and latter:

```
%prep
%{gpgverify} --keyring='%{SOURCE2}' --signature='%{SOURCE1}' --data='%{SOURCE0}'
%autosetup
```

Now for the time being I keep the line `%{gpgverify} ...` commented, otherwise the fedora-review 
systematically fails on copr, and no way to find out why, however the build is successful, only
the review fails and there is no log for that ... I am not familiar enough with using fedora-review 
in command line mode on my computer to get more info.

To complete the task there are many things that I need to learn, I apologize in advance if for some reason
I am not able to understand everything you do ... for now ;-)
Also I will likely take a break with this work for a few days, I am away from the lab (and my personal computer)
next week. I will be back the week after that.

Anyway thumbs up !

**Comment by alxpl** [comment]
GPG verification would be required only if you provided gpg-signed sources upstream. I hope you did not set up GPG just for the package…

**Comment by Slookeur** [comment]
... yes I did ... really though it was required ... too bad it took me hours to figure it out ... well hopefully I will use that someday ;-)

**Comment by alxpl** [comment]
It might help to look at other rpms, perhaps those using similar code, similar buildsystems, etc. to see how other spec files are structured and how different people have dealt with common issues: https://src.fedoraproject.org/

**Comment by Slookeur** [comment]
Oh thanks for the link, I try to come by such examples, but without knowing where to look this is kind of tricky. 
I will take the time to compare things and see how to improve my rpm.
If you are interested this is link for the last review from copr: 

https://download.copr.fedorainfracloud.org/results/slook/Atomes/fedora-36-x86_64/04879102-atomes/fedora-review/review.txt

Again thank you, I will have to stop for now, friends are about to come over for my Thursday night board game party ;-)

**Comment by alxpl** [comment]
Have fun!
I too have to go back to preparing for my interview…

**Comment by Slookeur** [comment]
Board games are over, that was fun, just back to my computer and read your message, 
good luck for the interview, if you are in the same field than me (physics/chem/material science), 
and the type of position your are applying for I might be able to give you some hints. 
Let me know, and best of luck.

**Pull request merged**
